### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sakurayuka** [sakurayuka/protospace-37783#1]
# URL
https://protospace-37783.herokuapp.com/

**Comment by shodai-ito** [comment]
@sakurayuka さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**`ユーザー管理機能`**
- [ ] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
表示はされておりますが、見本アプリとレイアウトが異なります。以下のURLをクリックすると見本アプリが見られますので、正しいレイアウトで実装しましょう。
https://protospace2020.herokuapp.com/

**`プロトタイプ編集機能`**
- [ ] **正しく編集できた場合は、詳細ページへ遷移すること**
編集が完了するとトップページへ遷移してしまいます。

**`ユーザー詳細機能`**
- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
コメント投稿者名をクリックすると、コメントの投稿主でなくプロトタイプの投稿主のページへ遷移してしまいます。

また、必須ではありませんが、以下の内容が見本アプリの仕様と異なります。

・ログアウト状態とログイン状態でトップページのレイアウトが異なる。
<img width="1200" alt="スクリーンショット 2022-06-26 9 20 04" src="https://user-images.githubusercontent.com/62537107/175794540-ba056b40-e945-458a-94d5-d5e427122af9.png">
<img width="1202" alt="スクリーンショット 2022-06-26 9 20 52" src="https://user-images.githubusercontent.com/62537107/175794547-5f4453fe-0d37-45e1-ba64-0c32fc437a34.png">

・プロトタイプが投稿されると、縦並びで表示される。
<img width="874" alt="スクリーンショット 2022-06-26 9 31 00" src="https://user-images.githubusercontent.com/62537107/175794649-64207ac0-afcd-44c9-add6-1f44dc5a0c2a.png">

アプリの仕様として上記も見本アプリに揃えていただくと、よりユーザー体験がよくなるかと思われます。
こちらは必須ではないため、修正の報告は不要です。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by sakurayuka** [comment]
修正し再提出しました。
見本アプリとの仕様が異なる見た目に関しては後ほど確認します。
よろしくお願いします

**Comment by motomuun** [comment]
@sakurayuka さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

見本アプリと仕様が異なる見た目に関しては、必須項目ではありませんのでLGTMとさせて頂きますが、
宜しければ復習も兼ねて取り組まれてみてください。

念の為以下に詳細を画像にて添付します。

**見本アプリ**
`一番上に「こんにちは◯◯さん」が表示されている`

<img width="1440" alt="スクリーンショット 2022-06-27 12 58 24" src="https://user-images.githubusercontent.com/65059944/175857533-de57efec-ec1f-4793-a451-e329fb15dd1f.png">

**現在の挙動**
`一番下に「こんにちは◯◯さん」が表示されている`

<img width="1440" alt="スクリーンショット 2022-06-27 12 58 53" src="https://user-images.githubusercontent.com/65059944/175857642-d5d82719-84ec-4e0d-952b-94c9469bd748.png">

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
